name: Upload release assets

permissions:
  contents: write

on:
  release:
    types:
      - created

jobs:
  build-deb:
    name: Create zip for publishing
    runs-on: self-hosted
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Create zip
        run: |
          cd solaar-extension@DarkFireVJ
          zip -r ../solaar-extension@DarkFireVJ.zip *
          cd ..

      - name: Upload package
        uses: DarkFireVJ/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./solaar-extension@DarkFireVJ.zip
          asset_name: solaar-extension@DarkFireVJ.zip
          tag: ${{ github.ref }}
